aca_shop_homepage:
    path:     /hello/{name}/{age}
    defaults: { _controller: AcaShopBundle:Default:index }


aca_login_route:
    path: /login_form
    defaults: { _controller: AcaShopBundle:Default:loginForm }
    methods: [GET, POST]

aca_login_handler:
    path: /process_login
    defaults: { _controller: AcaShopBundle:Default:processLogin }

aca_login2_route:
    path: /login_form2
    defaults: { _controller: AcaShopBundle:Login:loginForm}  # copy from Default to Login
    methods: [GET, POST]

# Do I need a logout route and a logout handler??
# aca_logout_route:
#     path: /login_form
#     defaults: { _controller: AcaShopBundle:Login:loginForm}  # copy from Default to Login
#     methods: [GET]




