services:
#    aca_shop.example:
#        class: AcaShopBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  acadb:
    class: Simplon\Mysql\Mysql
    arguments: [%database_host%, %database_user%, %database_password%, %database_name%]

  cart:
    class: AcaShopBundle\Service\CartService
    arguments:  [@acadb, @session, @model.cart]

    # now object will get correct parameters by @ referring to another service

  model.cart:
    class: AcaShopBundle\Model\Cart
    arguments: [@acadb]

  checkout:
    class: AcaShopBundle\Service\CheckoutService
    arguments:  [@acadb, @session, @cart]


  order:
    class: AcaShopBundle\Service\OrderService
    arguments:  [@acadb, @session, @cart]
